services:
  nginx:
    image: nginx:alpine
    ports:
      - "3443:443"  # HTTPS終端
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"  # nginx経由のみアクセス
    volumes:
      - .:/app
      - rails_bundle:/usr/local/bundle
    env_file:
      - .env
      - .env.local
    environment:
      - RAILS_ENV=development
      - SSL_ENABLED=false  # nginx側でSSL終端
    extra_hosts:
      - "host.docker.internal:host-gateway"  # RPコンテナからホストOSのIdPにアクセス（Linux用、Mac/Windowsでは自動サポート）

volumes:
  rails_bundle:
